language: python

python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'pypy'

env:
    - DJANGO="django>=1.8,<1.9"
    - DJANGO="django>=1.10,<1.11"
    - DJANGO="django>=1.11,<1.12"

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install ${DJANGO}

script:
    - python manage.py test

matrix:
  exclude:
    - python: "3.6"
      env: DJANGO="django>=1.8,<1.9"
    - python: "3.6"
      env: DJANGO="django>=1.10,<1.11"
